### ISSUE TITLE
"Borrow" items from ContribTracker?

### ISSUE THREAD

**Issue by damienmckenna** [mglaman/contribkanban.com#111]
Have you seen the ContribTracker project that husseinweb built?

https://code.axelerant.com/axelerant/contrib-tracker

They have some related goals, though their system is using content types vs custom entities.

**Comment by mglaman** [comment]
I haven't seen that. So that is more for tracking internal activity and interaction on Drupal.org?

The main goal for this is tracking work to be done, and to do.

With Node Boards (to be documented #112) it provides value found in https://github.com/mglaman/drupalorg-issue-tracker

**Comment by damienmckenna** [comment]
Right, Axelerant's contrib-tracker project is for internal tracking, with the intentions of expanding it to cover github too.

So, this might not really be relevant.
