### ISSUE TITLE
5/12/2019 - New account email could not be sent

### ISSUE THREAD

**Issue by laughnan** [mglaman/contribkanban.com#152]
Just created a new account (5/12/2019 at 12:10PM Pacific time) and the confirmation email could not be sent.

**Comment by mglaman** [comment]
I wonder if something got messed up on Amazon SES

**Comment by mglaman** [comment]
🤦‍♂️ I think I know the problem. The Swiftmailer overrides were in a settings.local.php on production. I need to replicate as environment variables

**Comment by mglaman** [comment]
@laughnan I finally got the emails fixed!

**Comment by laughnan** [comment]
Thanks @mglaman !! 👏
