### ISSUE TITLE
Unable to edit newly created custom board

### ISSUE THREAD

**Issue by laughnan** [mglaman/contribkanban.com#153]
I just created a new board for the DDI Website (https://contribkanban.com/node-board/f619cf7c-5196-4b43-927d-4c63e4385887). When I got to edit this board, I see a page saying that resource is not found:

<img width="1313" alt="Screen Shot 2019-05-12 at 12 12 22 PM" src="https://user-images.githubusercontent.com/918979/57586754-3c395580-74af-11e9-9bb0-9e643bbd77f7.png">

I am still authenticated:
<img width="1079" alt="Screen Shot 2019-05-12 at 12 12 28 PM" src="https://user-images.githubusercontent.com/918979/57586755-40657300-74af-11e9-8f04-bca24b33162f.png">

Might be related to me not having confirmed my account? The email wasn't able to be sent: https://github.com/mglaman/contribkanban.com/issues/152

**Comment by mglaman** [comment]
🤔 I wonder if it didn't assign ownership properly. This should be covered by Behat. But maybe not edit. Thanks for reporting

**Comment by mglaman** [comment]
Ah this was due to #132. It got added to the wrong user.

**Comment by mglaman** [comment]
@laughnan the board was re-assigned this should be fixed now. apologies!
