### ISSUE TITLE
Custom board doesn't display all items

### ISSUE THREAD

**Issue by shaal** [mglaman/contribkanban.com#167]
This is an example of a custom board:
https://contribkanban.com/node-board/450420fb-9f21-47ad-92f3-79520a84e581
![image](https://user-images.githubusercontent.com/22901/61587608-49cc2500-ab5b-11e9-8965-ed8e26576263.png)

Even that 11 issues are in that custom board, only 3 are being displayed:
![image](https://user-images.githubusercontent.com/22901/61587616-65cfc680-ab5b-11e9-87ee-d60b3e397c4a.png)

**Comment by mglaman** [comment]
So I realized before this didn't show things Closed (Fixed)

It'll be fixed in the new interface: https://app.contribkanban.com/node-board/450420fb-9f21-47ad-92f3-79520a84e581

**Comment by mglaman** [comment]
Actually, pushed a fix for the existing interface since it was a quick fix
