### ISSUE TITLE
Add a Drupal 8 Media sprint

### ISSUE THREAD

**Issue by davereid** [mglaman/contribkanban.com#17]
Right now we use the 'Media Initiative' tag, but we could use something simpler like 'D8Media' to help narrow it down. We have an upcoming sprint at NYC Camp in two weeks, it would be great if we could start using contribkanban for our sprints!

**Comment by mglaman** [comment]
Awesome! Want to give this a look over :)? http://contribkanban.com/#/sprint/mediaInitiative
