### ISSUE TITLE
Cannot create a custom sprint board

### ISSUE THREAD

**Issue by fantastic91** [mglaman/contribkanban.com#175]
Hi,

I wanted to use ContribKanban as a tool to follow https://www.drupal.org/project/issues/search?issue_tags=ContributionWeekend2020 drupal.org issues. It looks like the site does not allow creating the new sprint boards.

_Steps to reproduce_:

* Go to https://contribkanban.com/boards/sprint and add "ContributionWeekend2020" tag
* The page crashes with `ERR_TOO_MANY_REDIRECTS` error
* The same happens when accessing https://contribkanban.com/sprint/ContributionWeekend2020 directly

**Comment by mglaman** [comment]
Shoot. Okay, I'll try to see why. Thanks for reporting!

**Comment by mglaman** [comment]
Okay, maybe there's a browser cache thing, I can hit https://contribkanban.com/sprint/ContributionWeekend2020

**Comment by mglaman** [comment]
Nope. For some reason only my desktop worked, nothing else does

**Comment by mglaman** [comment]
There was some old code in here that tried to autopopulate boards, and it just caused problems. I've removed it, hopefully it is fixed. A new interface is coming.
