### ISSUE TITLE
Hardcoded user ID in menu link or cache issue

### ISSUE THREAD

**Issue by FlorentTorregrosa** [mglaman/contribkanban.com#181]
Hello,

I am testing to make a shared board, so I have created an account on https://contribkanban.com.

On the left sidebar, the "New board" link points to "https://contribkanban.com/user/65/node-boards/add", 65 is not my user ID.

**Comment by mglaman** [comment]
Argh, yeah this doesn't have the right cache contexts https://github.com/mglaman/contribkanban.com/blob/master/web/modules/custom/contribkanban_pages/src/Plugin/Menu/AddCustomBoardLink.php#L82

**Comment by mglaman** [comment]
This should fix it, and be deployed shortly https://github.com/mglaman/contribkanban.com/commit/28c751fa10a3381175a97b0667a1e904821cb906

**Comment by FlorentTorregrosa** [comment]
Hello,

Thanks for the fix. Confirming it works.

My bad, as the "Report a bug" links directly here, I didn't realize that the website code was public... I could have tried fixing it myself.
