### ISSUE TITLE
Custom board doesn't display name

### ISSUE THREAD

**Issue by hansfn** [mglaman/contribkanban.com#187]
First - thank you for an excellent service. I heard about it long time ago, but haven't started using it before now.

Project boards display the project name on the page - for example [Views Send](https://contribkanban.com/board/views_send) - but my newly created (private) custom board "[hansfn - core](https://contribkanban.com/node-board/d7be9596-1646-4561-9768-8a611bd9d695)" only displays the name as part of the tab name.

**Comment by mglaman** [comment]
Ah, forgot to add that to the issue collection board component, thanks

**Comment by mglaman** [comment]
Forgot to tag this in the commit, was fixed in https://github.com/mglaman/contribkanban.com/commit/fac7a30b61e24c7c51217e47cc94f74a344e2fb5
