### ISSUE TITLE
Show currently assigned user?

### ISSUE THREAD

**Issue by davereid** [mglaman/contribkanban.com#19]
It would be nice to know if an issue is assigned or not. I like Trello's way of showing the user picture of the assignee.

**Comment by mglaman** [comment]
I dig this. Only issue is just Drupal.org and the restws module return resource URLs, not the object. Maybe I'll add a user cache for users (currently only caching API requests for issue results)

**Comment by mglaman** [comment]
Apparently the API doesn't return picture URLs! going to open a ticket for that

**Comment by mglaman** [comment]
This is deployed and picture will be an enhancement once API provides it ( #20 )
