### ISSUE TITLE
Core component: ajax system

### ISSUE THREAD

**Issue by mglaman** [mglaman/contribkanban.com#38]
Drupal core is so large the different components have their own boards: bugs and tasks. In order for the boards to show up, we need their config JSON file in `app/config/boards/core/`. Right now there is still a manual process with adding an entry on Parse.com. But the more tedious task is JSON creation.

Reference this commit: @ea4231deed8d7e05c6b55f7728777d6f2d27eee7 for an example of making a Core component config.

**Comment by tloudon** [comment]
@mglaman can you expand on this?  I don't mind creating a JSON file...just looking for a little guidance so I don't have to muck around the codebase to see how the fields are used in-depth and/or the d.o API to find the field info.  THANKS!

**Comment by mglaman** [comment]
Basically a PR of this file https://github.com/mglaman/contribkanban.com/blob/ea4231deed8d7e05c6b55f7728777d6f2d27eee7/app/config/boards/core/d8_entity_bugs.json, but change "entity" to "ajax", then I'll add record in Parse. Still split between Parse.com records + config in JSON
