### ISSUE TITLE
#issue number clicks open two windows

### ISSUE THREAD

**Issue by tloudon** [mglaman/contribkanban.com#51]
Hey @mglaman 

The md-card openIssue() function is capturing any click on the card to open a window for the project.  If you click on the actual href 
![screen shot 2015-10-03 at 8 52 15 am](https://cloud.githubusercontent.com/assets/415007/10263697/2dd28f5a-69ac-11e5-9dcc-d7f19575edf1.jpg)
you get the href action + the md-card action, so dupe windows/tabs.

IDK what the best UX is here, but I'm thinking if you remove the href value https://github.com/mglaman/contribkanban.com/blob/99b2eef2d5276bd1f750c5a541f848d2a2dff7d8/app/scripts/directives.js#L81 ie, href='' .  The link won't open a window but will still show up as a link.  You could also do a preventDefault() on the md-card a click().  Additionally, maybe it would be nice to add a "cursor: pointer" to https://github.com/mglaman/contribkanban.com/blob/bf7596c3a0d2fa89d39dc2c5aa625de623eabe81/app/styles/main.scss#L108 so it's clear the entire card is a clickable (and not draggable b/c teh trellos)

Does that make sense?  You want me to open a PR for this?

cheers

**Comment by mglaman** [comment]
If you want to open PR that'd be slick. I noticed this myself, but popup blocker caught it. Maybe if href was removed and just cursor added.

**Comment by tloudon** [comment]
saw the merge. closing :)

**Comment by mglaman** [comment]
Pft, way to go GitHub. Thought it closed if merged. Thanks
