### ISSUE TITLE
Need to purge CloudFlare cache on build deployment

### ISSUE THREAD

**Issue by mglaman** [mglaman/contribkanban.com#54]
There isn't an integration with CloudFlare, but the build process needs to ping some kind of webhook to purge the CloudFlare cache. It seems to get wonky after every build.

**Comment by tloudon** [comment]
@mglaman see https://api.cloudflare.com/#zone-purge-individual-files-by-url-and-cache-tags

if you email me the creds I can probably set up a grunt task to hit the CF API using an environmental variable...not sure if that's idiomatic js/grunt but it's probably how I would handle the task in other setups.

Also, all we would need to purge is index.html, right?  All dependent assets are fingerprinted, right?

**Comment by mglaman** [comment]
Merged in a fix using grunt-cloudflare
