### ISSUE TITLE
"Invalid machine name" when adding a project

### ISSUE THREAD

**Issue by tonystar** [mglaman/contribkanban.com#56]
First of all — thank you for making Kanban boards for Drupal community! Really like your solution.

I would like to try your boards for my contributions but it just tells me "Invalid machine name".

Tried with `tree` and `bricks` but both failed to add. Please help!

**Comment by mglaman** [comment]
Ah, I think the error here *isn't* the machine name but lack of releases. I thought I had fixed this before. I'll give a peak in the next few days, I've been away and have to catch up on a few things.

**Comment by tonystar** [comment]
Hm. No, it just does not work. Tested with other contributions as well.

Please help! Really want these board for my projects!

**Comment by mglaman** [comment]
@tonystar I'll be able to look at this tomorrow

**Comment by tonystar** [comment]
@mglaman thanks! Looking forward!

**Comment by tonystar** [comment]
@mglaman any news on that? I already released my contrib (http://dgo.to/bricks), but it was so disorganized w/o your board...

**Comment by mglaman** [comment]
So I think the error is farce, http://contribkanban.com/board/bricks. It's saying there is an error but adding anyways.

**Comment by tonystar** [comment]
@mglaman cool, feel much better ;) this issue is becoming minor... but anyway should be fixed, right?

**Comment by mglaman** [comment]
Yes, it'll get fixed. I'd love to be able to drop my paid client work and fix it, but this is a "labor of love" that doesn't let me put food on the table for my family ;)

**Comment by tonystar** [comment]
Yeah, beautifully said! We all understand, so thank you for a great job anyway!

**Comment by mglaman** [comment]
@tonystar for some reason a promise isn't resolving as expected. Which is weird because board autocreation is working.
