### ISSUE TITLE
Columes limited to 75 items

### ISSUE THREAD

**Issue by jurgenhaas** [mglaman/contribkanban.com#66]
It appears that each column in the board is limited to 75 items, right? If true it would be better to remove that limit so that we get a real overview on volume, especially on what's been worked on.

**Comment by mglaman** [comment]
They are currently limited to 75 because

1) There isn't paging setup yet in code
2) There needs to be a lazy load implemented when scrolling a list

**Comment by jonathan1055** [comment]
That's interesting. Currently 'No port active', 'work started' and 'alpha/beta' have 75 items, but 'stable release' has 79 items.

Also, what is the criteria for picking the 75? I looked earlier today in https://contribkanban.com/board/contrib_tracker (D7 to D8 porting tracking) for the [Scheduler module](https://www.drupal.org/project/scheduler) module (in 92nd place ordered by number of installs) and did not find. Other modules which were being shown this morning are not showing now, so there must be some quite dynamic method for picking them?

Great work, though. This is a very nice way to display an issue queue.

**Comment by mglaman** [comment]
Before it was just 50, but that wasn't enough.

Also, the REST API does not support AND/OR queries, so if a column is 2 statuses, it is two REST calls.

**Comment by jonathan1055** [comment]
Thanks. Yes the two status to one column explains it. There are 4 'fixed' and 75 'closed(fixed)' making 79 for that column.

I can't work out how the items are sorted though. Is there one selection criteria for picking the 75, then another for ordering them.

**Comment by mglaman** [comment]
@jonathan1055 so I'm pretty sure the boards are sorting by priority.. but I can't recall what I'm doing in the REST call. I was working through a big refactor and clean up, but things got busy over on my end

**Comment by mglaman** [comment]
I've bumped the limit to 100. Ideally I'd like a way to implement autoloading if reaching the bottom. But big problem is lack of AND/OR :/

**Comment by mglaman** [comment]
AND/OR landed, so I could probably bump this more

**Comment by mglaman** [comment]
This is outdated. Limit is at 100 per request.
