### ISSUE TITLE
Customizable Column Order

### ISSUE THREAD

**Issue by smmccabe** [mglaman/contribkanban.com#71]
I prefer a active->needs work->needs review type flow, so it would be nice to be able to customize the column order. Per board at least, but maybe even per user?

**Comment by mglaman** [comment]
Right now project boards can be customized any which way https://github.com/mglaman/contribkanban.com/tree/master/config/boards

That's how there is `commerce2x` and `commerce`, but tag/sprint boards do not follow this. They should.
