### ISSUE TITLE
Which tag is used for the Media initiative board?

### ISSUE THREAD

**Issue by slashrsm** [mglaman/contribkanban.com#80]
We used to use "Media initiative" tag, but recently standardized on "D8Media" (as already mentioned in #17). I suspect that the board still uses the old tag. 

Could you check that and update if necessary?

Thank you for your hard work with this great tool!

**Comment by mglaman** [comment]
@slashrsm the old board still exists: https://contribkanban.com/sprint/d8Media

I can drop the old one.

**Comment by slashrsm** [comment]
Yes, please do. D8Media is now the only tag that we're using. Thanks!

**Comment by slashrsm** [comment]
Thanks!
